.\"Created with GNOME Manpages Editor Wizard
.TH sphinx-spelldump 1 "May 12, 2009" "" "SQL Full Text search engine"

.SH NAME
sphinx-spelldump \- SQL Full Text search engine dictionary generator

.SH SYNOPSIS
.B sphinx-spelldump

.PP
Sphinx 0.9.8.1\-release (r1533)
Copyright (c) 2001\-2008, Andrew Aksyonoff

